# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SBAInspectableHitExtensionDemo' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for SBAInspectableHitExtensionDemo
  pod 'UIButton+SBAInspectableHitExtension', :git => 'https://github.com/shoaib-akhtar/UIButton-InspectableHitExtension'
end
